### ISSUE TITLE
Looking for Vision-8B-MiniCPM-2_5-Uncensored-and-Detailed

### ISSUE THREAD

**Issue by mashdragon** [OpenBMB/llama.cpp#17]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

I am looking for a copy of https://huggingface.co/CausalLM/Vision-8B-MiniCPM-2_5-Uncensored-and-Detailed, which was taken offline. There is a 4-byte version (which we'd hope is correct and not malware) here: https://huggingface.co/sdasd112132/Vision-8B-MiniCPM-2_5-Uncensored-and-Detailed-4bit

Pinging individuals who discussed this repo (hopefully you have a copy!):
@cybertimon
@win10ogod

### Motivation

I'd really like to see what a high-output OCR model can do. If anyone is able to get the model to me, I will make it available for download for a long time, maybe as torrent.

**Comment by CyberTimon** [comment]
Yes, I still have the original unquantized FP16 model on my server. I can re-upload it on another platform. Can you recommend a platform? He doesn't want it back on huggingface.

**Comment by mashdragon** [comment]
> Yes, I still have the original unquantized FP16 model on my server. I can re-upload it on another platform. Can you recommend a platform? He doesn't want it back on huggingface.

Wow, thank you so much for offering! I think for something like this, either https://archive.org/ or offering a torrent magnet link would work best.

Edit: It appears that archive.org creates torrents automatically, so uploading there would accomplish both.

**Comment by CyberTimon** [comment]
It's uploading now (to archive.org) but it will take a while. Will ping you when it's done.

**Comment by CyberTimon** [comment]
Here you have it: https://archive.org/details/Vision-8B-MiniCPM-2_5-Uncensored-and-Detailed

Hope it works! Have fun. All credits go to Josephus Cheung for this amazing model.

**Comment by mashdragon** [comment]
Thank you so much for going out of your way to upload it! I am so grateful! With this unquantized version, I think it should work with the OpenBMB/minicpm llama.cpp (this repo).

**Comment by CyberTimon** [comment]
I'm glad it worked for you. How are you going to quantize it? I've tried it before but I only got errors with 4bit / 8bit bitsandbytes.

**Comment by mashdragon** [comment]
> I'm glad it worked for you. How are you going to quantize it? I've tried it before but I only got errors with 4bit / 8bit bitsandbytes.

I am able to create a GGUF and quantize it using the guide here: https://github.com/OpenBMB/llama.cpp/tree/minicpm-v2.5/examples/minicpmv#minicpm-llama3-v-25

I couldn't get the same long output using my GGUF after quantizing to Q4_K_M however.
