### ISSUE TITLE
convert model to gguf failed

### ISSUE THREAD

**Issue by yancaoweidaode** [OpenBMB/llama.cpp#20]
### What happened?

File not found: path/model/tokenizer.model,  Cannot find Llama BPE tokenizer

### Name and Version

python convert_hf_to_gguf.py /path/to/model

**Comment by tc-mb** [comment]
Hi, I don't always pay attention to the issue area in this fork code repo.

If this issue still needs to be answered, please raise an issue in the [main repo](https://github.com/OpenBMB/MiniCPM-V) with "llamacpp" label. I will respond very quickly.
If this issue no longer needs to be answered, I will close it this week.
