### ISSUE TITLE
2.6版本编译的时候ffmpeg报错

### ISSUE THREAD

**Issue by dingtine** [OpenBMB/llama.cpp#22]
### Background Description

下面这段makefile中的代码报错，我理解是不是ffmpeg安装后，那里没有配置对。
试了很多种方案都没解决，求教。（之前的2.5没有这个模块，一直正常）

报错：
[ 66%] Building CXX object examples/llava/CMakeFiles/llama-minicpmv-cli.dir/minicpmv-cli.cpp.o
/Users/tine/llama.cpp/examples/llava/minicpmv-cli.cpp:13:14: fatal error: 'libavcodec/avcodec.h' file not found
    #include <libavcodec/avcodec.h>
             ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [examples/llava/CMakeFiles/llama-minicpmv-cli.dir/minicpmv-cli.cpp.o] Error 1
make[1]: *** [examples/llava/CMakeFiles/llama-minicpmv-cli.dir/all] Error 2
make: *** [all] Error 2

原始makefile中的代码
FFMPEG_CFLAGS := $(shell pkg-config --cflags libavformat libavcodec libavutil)
FFMPEG_LIBS := $(shell pkg-config --libs libavformat libavcodec libavutil) -lswscale

llama-minicpmv-cli: examples/llava/minicpmv-cli.cpp examples/llava/clip.h examples/llava/clip.cpp examples/llava/llava.h examples/llava/llava.cpp ggml.o llama.o $(COMMON_DEPS) $(OBJS)
	$(CXX) $(CXXFLAGS) $(FFMPEG_CFLAGS) -c $< -o $(call GET_OBJ_FILE, $<)
	$(CXX) $(CXXFLAGS) $(FFMPEG_CFLAGS) -c examples/llava/clip.cpp  -o $(call GET_OBJ_FILE, examples/llava/clip.cpp) -Wno-cast-qual
	$(CXX) $(CXXFLAGS) $(FFMPEG_CFLAGS) -c examples/llava/llava.cpp -o $(call GET_OBJ_FILE, examples/llava/llava.cpp)
	$(CXX) $(CXXFLAGS) $(FFMPEG_CFLAGS) $(filter-out %.h $< examples/llava/clip.cpp examples/llava/llava.cpp,$^) $(call GET_OBJ_FILE, $<) $(call GET_OBJ_FILE, examples/llava/clip.cpp) $(call GET_OBJ_FILE, examples/llava/llava.cpp) -o $@ $(LDFLAGS) $(FFMPEG_LIBS)

**Comment by tc-mb** [comment]
> ### Background Description
> 下面这段makefile中的代码报错，我理解是不是ffmpeg安装后，那里没有配置对。 试了很多种方案都没解决，求教。（之前的2.5没有这个模块，一直正常）
> 
> 报错： [ 66%] Building CXX object examples/llava/CMakeFiles/llama-minicpmv-cli.dir/minicpmv-cli.cpp.o /Users/tine/llama.cpp/examples/llava/minicpmv-cli.cpp:13:14: fatal error: 'libavcodec/avcodec.h' file not found #include <libavcodec/avcodec.h> ^~~~~~~~~~~~~~~~~~~~~~ 1 error generated. make[2]: *** [examples/llava/CMakeFiles/llama-minicpmv-cli.dir/minicpmv-cli.cpp.o] Error 1 make[1]: *** [examples/llava/CMakeFiles/llama-minicpmv-cli.dir/all] Error 2 make: *** [all] Error 2
> 
> 原始makefile中的代码 FFMPEG_CFLAGS := $(shell pkg-config --cflags libavformat libavcodec libavutil) FFMPEG_LIBS := $(shell pkg-config --libs libavformat libavcodec libavutil) -lswscale
> 
> llama-minicpmv-cli: examples/llava/minicpmv-cli.cpp examples/llava/clip.h examples/llava/clip.cpp examples/llava/llava.h examples/llava/llava.cpp ggml.o llama.o (COMMONDEPS)(OBJS) (CXX)(CXXFLAGS) (FFMPEGCFLAGS)−c&lt; -o (callGETOBJFILE,&lt;) (CXX)(CXXFLAGS) (FFMPEGCFLAGS)−cexamples/llava/clip.cpp−o(call GET_OBJ_FILE, examples/llava/clip.cpp) -Wno-cast-qual (CXX)(CXXFLAGS) (FFMPEGCFLAGS)−cexamples/llava/llava.cpp−o(call GET_OBJ_FILE, examples/llava/llava.cpp) (CXX)(CXXFLAGS) (FFMPEGCFLAGS)(filter-out %.h <examples/llava/clip.cppexamples/llava/llava.cpp,^) (callGETOBJFILE,&lt;) (callGETOBJFILE,examples/llava/clip.cpp)(call GET_OBJ_FILE, examples/llava/llava.cpp) -o @(LDFLAGS) $(FFMPEG_LIBS)
> 
> ### Possible Refactor Approaches
> _No response_

Please do not use this issue area, but use the [main repo issue area](https://github.com/OpenBMB/MiniCPM-V/issues).

please raise an issue in the [main repo](https://github.com/OpenBMB/MiniCPM-V) with "llamacpp" label. I will respond ASAP.

**Comment by bigcyy** [comment]
一样的问题，我 pkg i ffmpeg 后报其他错误。

**Comment by Single430** [comment]
win 下同样的错误
然后在docker中linux下make，同样错误，然后使用下面解决问题
```
apt install pkg-config
apt install libavformat-dev
apt install libavcodec-dev
apt install libswresample-dev
apt install libswscale-dev
apt install libavutil-dev

make clean
make -j 8
```
