### ISSUE TITLE
bug:在termux上运行minicpm出现ggml_can_repeat报错

### ISSUE THREAD

**Issue by Cosmos2023** [OpenBMB/llama.cpp#25]
### What happened?

当我在我的手机上使用termux部署多模态的时候出现了一个bug，我的手机型号是iqoo12 RAM:12g
命令行为
` ./minicpmv-cli -m ~/model/ggml-model-Q4_K_M.gguf --mmproj ~/model/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image ../../media/matmul.png  -p "What is in the image?"`
错误日志如下：
`clip_model_load: - type  f32:  285 tensors

clip_model_load: - type  f16:  170 tensors

clip_model_load: CLIP using CPU backend

clip_model_load: text_encoder:   0

clip_model_load: vision_encoder: 1

clip_model_load: llava_projector:  1

clip_model_load: model size:     996.02 MB

clip_model_load: metadata size:  996.19 MB

clip_model_load: params backend buffer size =  996.02 MB (455 tensors)

key clip.vision.image_grid_pinpoints not found in file

key clip.vision.mm_patch_merge_type not found in file

key clip.vision.image_crop_resolution not found in file

clip_image_build_graph: ctx->buf_compute_meta.size(): 884880

clip_image_build_graph: load_image_size: 448 448

GGML_ASSERT: /data/data/com.termux/files/home/llama.cpp-minicpm-v2.5/ggml.c:4344: ggml_can_repeat(b, a)

Aborted`

同样的问题也出现在这条issue中
`https://github.com/OpenBMB/MiniCPM-V/issues/382#issuecomment-2276981255`
请问该如何解决呢，谢谢

### Name and Version

 $ ./minicpmv-cli --version
version: 0 (unknown)
built with Android (dev, +pgo, +bolt, +lto, -mlgo, based on r487747d) clang version 17.0.2 (https://android.googlesource.com/toolchain/llvm-project d9f89f4d16663d5012e5c09495f3b30ece3d2362) for aarch64-unknown-linux-android28

**Comment by lzd19981105** [comment]
您好，在进行到在build-android文件夹里进行make的时候，您有出现过fatal error: 'libavcodec/avcodec.h' 这样的错误吗？有的话，您是怎么解决的呢？谢谢。

**Comment by mailonghua** [comment]
> 您好，在进行到在build-android文件夹里进行make的时候，您有出现过fatal error: 'libavcodec/avcodec.h' 这样的错误吗？有的话，您是怎么解决的呢？谢谢。

请问这个问题你解决了吗
