### ISSUE TITLE
Bug: 运行MiniCPM-V-2_6-gguf出错

### ISSUE THREAD

**Issue by ly19970621** [OpenBMB/llama.cpp#29]
### What happened?

运行
`./llama-minicpmv-cli -m /workspace/OpenBMB/MiniCPM-V-2_6-gguf/ggml-model-f16.gguf --mmproj /workspace/OpenBMB/MiniCPM-V-2_6-gguf/ggml-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image ../70.png -p "What is in the image?"`

出现

`Log start
key general.description not found in file
terminate called after throwing an instance of 'std::runtime_error'
  what():  Missing required key: general.description
Aborted (core dumped)`

请问这个是什么问题？

### Name and Version

`./llama-cli --version`

`version: 0 (unknown)
built with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for x86_64-linux-gnu`

**Comment by Doraemonwei** [comment]
哥们你解决了吗？我也碰到了

**Comment by Doraemonwei** [comment]
哥们你运行命令有问题
./llama-minicpmv-cli -m /workspace/OpenBMB/MiniCPM-V-2_6-gguf/ggml-model-f16.gguf --mmproj /workspace/OpenBMB/MiniCPM-V-2_6-gguf/ggml-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image ../70.png -p "What is in the image?"
 --mmproj后面跟的应该是一个多模态的模型，参考https://huggingface.co/openbmb/MiniCPM-o-2_6-gguf
 --mmproj 后面因该是应该的那个1G大小的多模态模型mmproj-model-f16.gguf
