### ISSUE TITLE
build on windows

### ISSUE THREAD

**Issue by muwei1989** [OpenBMB/llama.cpp#4]
how to build minicpmv-cli on windows ?

**Comment by tc-mb** [comment]
> how to build minicpmv-cli on windows ?

Maybe you can try this.

- On Windows:

    1. Download the latest fortran version of [w64devkit](https://github.com/skeeto/w64devkit/releases).
    2. Extract `w64devkit` on your pc.
    3. Run `w64devkit.exe`.
    4. Use the `cd` command to reach the `llama.cpp` folder.
    5. From here you can run:
        ```bash
        make
        ```

Or refer to the different build schemes for the window environment in llama.cpp 's readme. https://github.com/ggerganov/llama.cpp/edit/master/README.md

**Comment by henrywang0314** [comment]
> > how to build minicpmv-cli on windows ?
> 
> Maybe you can try this.
> 
> * On Windows:
>   
>   1. Download the latest fortran version of [w64devkit](https://github.com/skeeto/w64devkit/releases).
>   2. Extract `w64devkit` on your pc.
>   3. Run `w64devkit.exe`.
>   4. Use the `cd` command to reach the `llama.cpp` folder.
>   5. From here you can run:
>      ```shell
>      make
>      ```
> 
> Or refer to the different build schemes for the window environment in llama.cpp 's readme. https://github.com/ggerganov/llama.cpp/edit/master/README.md

I've tried this:
Here is the error log:
~/Documents/Visual_Studio_Project/llama.cpp $ make
I ccache not found. Consider installing it for faster compilation.
I llama.cpp build info:
I UNAME_S:   Windows_NT
I UNAME_P:   unknown
I UNAME_M:   x86_64
I CFLAGS:    -I. -Icommon -D_XOPEN_SOURCE=600 -DNDEBUG -D_WIN32_WINNT=0x602 -DGGML_USE_LLAMAFILE  -std=c11   -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Werror=implicit-function-declaration -march=native -mtune=native -Xassembler -muse-unaligned-vector-move -Wdouble-promotion
I CXXFLAGS:  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -Xassembler -muse-unaligned-vector-move  -march=native -mtune=native -Wno-array-bounds -Wno-format-truncation -Wextra-semi -I. -Icommon -D_XOPEN_SOURCE=600 -DNDEBUG -D_WIN32_WINNT=0x602 -DGGML_USE_LLAMAFILE
I NVCCFLAGS: -std=c++11 -O3
I LDFLAGS:
I CC:        cc (GCC) 14.1.0
I CXX:       c++ (GCC) 14.1.0

cc  -I. -Icommon -D_XOPEN_SOURCE=600 -DNDEBUG -D_WIN32_WINNT=0x602 -DGGML_USE_LLAMAFILE  -std=c11   -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Werror=implicit-function-declaration -march=native -mtune=native -Xassembler -muse-unaligned-vector-move -Wdouble-promotion    -c ggml.c -o ggml.o
In file included from ggml.c:4:
ggml.c: In function 'ggml_fp32_to_bf16_row':
ggml.c:411:19: error: incompatible type for argument 2 of '_mm512_storeu_si512'
  411 |             m512i(_mm512_cvtne2ps_pbh(_mm512_loadu_ps(x + i + 16),
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                   |
      |                   __m512bh
  412 |                                 _mm512_loadu_ps(x + i))));
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~
ggml-impl.h:23:18: note: in definition of macro 'm512i'
   23 | #define m512i(p) p
      |                  ^
In file included from C:/Users/henry/Downloads/w64devkit-fortran-1.23.0/w64devkit/lib/gcc/x86_64-w64-mingw32/14.1.0/include/immintrin.h:55,
                 from C:/Users/henry/Downloads/w64devkit-fortran-1.23.0/w64devkit/lib/gcc/x86_64-w64-mingw32/14.1.0/include/x86intrin.h:32,
                 from C:/Users/henry/Downloads/w64devkit-fortran-1.23.0/w64devkit/x86_64-w64-mingw32/include/intrin.h:6
,
                 from ggml-impl.h:443:
C:/Users/henry/Downloads/w64devkit-fortran-1.23.0/w64devkit/lib/gcc/x86_64-w64-mingw32/14.1.0/include/avx512fintrin.h:9489:41: note: expected '__m512i' {aka '__vector(8) long long int'} but argument is of type '__m512bh'
 9489 | _mm512_storeu_si512 (void *__P, __m512i __A)
      |                                 ~~~~~~~~^~~
ggml.c: In function 'ggml_vec_dot_bf16':
ggml.c:1850:42: error: incompatible type for argument 2 of '_mm512_dpbf16_ps'
 1850 |         c1 = _mm512_dpbf16_ps(c1, m512bh(_mm512_loadu_si512((x + i))),
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                          |
      |                                          __m512i {aka __vector(8) long long int}
ggml-impl.h:22:19: note: in definition of macro 'm512bh'
   22 | #define m512bh(p) p
      |                   ^
In file included from C:/Users/henry/Downloads/w64devkit-fortran-1.23.0/w64devkit/lib/gcc/x86_64-w64-mingw32/14.1.0/include/immintrin.h:131:
C:/Users/henry/Downloads/w64devkit-fortran-1.23.0/w64devkit/lib/gcc/x86_64-w64-mingw32/14.1.0/include/avx512bf16intrin.h:113:40: note: expected '__m512bh' but argument is of type '__m512i' {aka '__vector(8) long long int'}
  113 | _mm512_dpbf16_ps (__m512 __A, __m512bh __B, __m512bh __C)
      |                               ~~~~~~~~~^~~
ggml.c:1851:37: error: incompatible type for argument 3 of '_mm512_dpbf16_ps'
 1851 |                              m512bh(_mm512_loadu_si512((y + i))));
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                     |
      |                                     __m512i {aka __vector(8) long long int}
ggml-impl.h:22:19: note: in definition of macro 'm512bh'
   22 | #define m512bh(p) p
      |                   ^
C:/Users/henry/Downloads/w64devkit-fortran-1.23.0/w64devkit/lib/gcc/x86_64-w64-mingw32/14.1.0/include/avx512bf16intrin.h:113:54: note: expected '__m512bh' but argument is of type '__m512i' {aka '__vector(8) long long int'}
  113 | _mm512_dpbf16_ps (__m512 __A, __m512bh __B, __m512bh __C)
      |                                             ~~~~~~~~~^~~
ggml.c:1852:42: error: incompatible type for argument 2 of '_mm512_dpbf16_ps'
 1852 |         c2 = _mm512_dpbf16_ps(c2, m512bh(_mm512_loadu_si512((x + i + 32))),
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                          |
      |                                          __m512i {aka __vector(8) long long int}
ggml-impl.h:22:19: note: in definition of macro 'm512bh'
   22 | #define m512bh(p) p
      |                   ^
C:/Users/henry/Downloads/w64devkit-fortran-1.23.0/w64devkit/lib/gcc/x86_64-w64-mingw32/14.1.0/include/avx512bf16intrin.h:113:40: note: expected '__m512bh' but argument is of type '__m512i' {aka '__vector(8) long long int'}
  113 | _mm512_dpbf16_ps (__m512 __A, __m512bh __B, __m512bh __C)
      |                               ~~~~~~~~~^~~
ggml.c:1853:37: error: incompatible type for argument 3 of '_mm512_dpbf16_ps'
 1853 |                              m512bh(_mm512_loadu_si512((y + i + 32))));
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                     |
      |                                     __m512i {aka __vector(8) long long int}
ggml-impl.h:22:19: note: in definition of macro 'm512bh'
   22 | #define m512bh(p) p
      |                   ^
C:/Users/henry/Downloads/w64devkit-fortran-1.23.0/w64devkit/lib/gcc/x86_64-w64-mingw32/14.1.0/include/avx512bf16intrin.h:113:54: note: expected '__m512bh' but argument is of type '__m512i' {aka '__vector(8) long long int'}
  113 | _mm512_dpbf16_ps (__m512 __A, __m512bh __B, __m512bh __C)
      |                                             ~~~~~~~~~^~~
make: *** [Makefile:693: ggml.o] Error 1

> > how to build minicpmv-cli on windows ?
> 
> Maybe you can try this.
> 
> * On Windows:
>   
>   1. Download the latest fortran version of [w64devkit](https://github.com/skeeto/w64devkit/releases).
>   2. Extract `w64devkit` on your pc.
>   3. Run `w64devkit.exe`.
>   4. Use the `cd` command to reach the `llama.cpp` folder.
>   5. From here you can run:
>      ```shell
>      make
>      ```
> 
> Or refer to the different build schemes for the window environment in llama.cpp 's readme. https://github.com/ggerganov/llama.cpp/edit/master/README.md

**Comment by tc-mb** [comment]
@all 
Hi, I don't always pay attention to the issue area in this fork code repo.
1. If this issue still needs to be answered, please raise an issue in the [main repo](https://github.com/OpenBMB/MiniCPM-V) with "llamacpp" label. I will respond very quickly.
2. If this issue no longer needs to be answered, I will close it this week.
