### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by mzwing** [OpenBMB/llama.cpp#5]
When I tried to build it, I got some strange errors...

Log here: <https://github.com/MZWNET/actions/actions/runs/9226425626/job/25386167551>

**Comment by tc-mb** [comment]
> When I tried to build it, I got some strange errors...
> 
> Log here: https://github.com/MZWNET/actions/actions/runs/9226425626/job/25386167551

Can you try to "make" under the environment or send me the environment you use?

**Comment by mzwing** [comment]
> Can you try to "make" under the environment or send me the environment you use?

Thanks for your reply, and sorry for my late.

You can easily find my action file at <https://github.com/MZWNET/actions/blob/master/.github/workflows/llama_cpp_minicpm_v2.5.yml>.

BTW I notice that my original llama.cpp build also encountered build error, so it should not be the repo's fault.
