### ISSUE TITLE
请问支持接口形式的调用吗？

### ISSUE THREAD

**Issue by Single430** [OpenBMB/llama.cpp#6]
我试了server，有个参数不支持，然后minicpm-cli中也没有相应支持

**Comment by tc-mb** [comment]
> 我试了server，有个参数不支持，然后minicpm-cli中也没有相应支持

应该是还不支持，我还没调到这。

**Comment by awfty** [comment]
> > 我试了server，有个参数不支持，然后minicpm-cli中也没有相应支持
> 
> 应该是还不支持，我还没调到这。
有计划支持吗？谢谢

**Comment by tc-mb** [comment]
@all 
Hi, I don't always pay attention to the issue area in this fork code repo.
1. If this issue still needs to be answered, please raise an issue in the [main repo](https://github.com/OpenBMB/MiniCPM-V) with "llamacpp" label. I will respond very quickly.
2. If this issue no longer needs to be answered, I will close it this week.
