### ISSUE TITLE
Bug: 在wsl环境下编译异常 make: *** [Makefile:925: common/build-info.cpp] Error 2

### ISSUE THREAD

**Issue by hyphantom** [OpenBMB/llama.cpp#9]
### What happened?

运行make时出现异常 
该问题在win11的wsl2下发生，本来希望解决win11环境下的各种终端无法使用中文，故尝试使用wsl环境
在win11环境下编译通过 使用Q4gguf没问题。但是可能是cmd编码问题，我中文提问报非法输入，诱导的中文回答也是乱码
下面的log区是实际的输出，其中包含了环境信息

### Name and Version

wsl2 -ubuntu 22.04
cpu intel 13900hx
gpu nv rtx4070m 8G

### Relevant log output

```shell
llama.cpp# make
I ccache not found. Consider installing it for faster compilation.
I llama.cpp build info: 
I UNAME_S:   Linux
I UNAME_P:   x86_64
I UNAME_M:   x86_64
I CFLAGS:    -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_LLAMAFILE  -std=c11   -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Werror=implicit-function-declaration -pthread -march=native -mtune=native -Wdouble-promotion
I CXXFLAGS:  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -pthread  -march=native -mtune=native -Wno-array-bounds -Wno-format-truncation -Wextra-semi -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_LLAMAFILE
I NVCCFLAGS: -std=c++11 -O3
I LDFLAGS:
I CC:        cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
I CXX:       c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

cc  -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_LLAMAFILE  -std=c11   -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Werror=implicit-function-declaration -pthread -march=native -mtune=native -Wdouble-promotion    -c ggml.c -o ggml.o
c++ -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -pthread  -march=native -mtune=native -Wno-array-bounds -Wno-format-truncation -Wextra-semi -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_LLAMAFILE  -c llama.cpp -o llama.o
c++ -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -pthread  -march=native -mtune=native -Wno-array-bounds -Wno-format-truncation -Wextra-semi -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_LLAMAFILE  -c common/common.cpp -o common.o   
c++ -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -pthread  -march=native -mtune=native -Wno-array-bounds -Wno-format-truncation -Wextra-semi -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_LLAMAFILE  -c common/sampling.cpp -o sampling.o
c++ -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -pthread  -march=native -mtune=native -Wno-array-bounds -Wno-format-truncation -Wextra-semi -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_LLAMAFILE  -c common/grammar-parser.cpp -o grammar-parser.o
: not foundld-info.sh: 2: 
: not foundld-info.sh: 4:
: not foundld-info.sh: 9:
scripts/build-info.sh: 31: Syntax error: end of file unexpected (expecting "then")
make: *** [Makefile:925: common/build-info.cpp] Error 2
```

**Comment by tc-mb** [comment]
> ### What happened?
> 运行make时出现异常 该问题在win11的wsl2下发生，本来希望解决win11环境下的各种终端无法使用中文，故尝试使用wsl环境 在win11环境下编译通过 使用Q4gguf没问题。但是可能是cmd编码问题，我中文提问报非法输入，诱导的中文回答也是乱码 下面的log区是实际的输出，其中包含了环境信息
> 
> ### Name and Version
> wsl2 -ubuntu 22.04 cpu intel 13900hx gpu nv rtx4070m 8G
> 
> ### What operating system are you seeing the problem on?
> _No response_
> 
> ### Relevant log output
> ```shell
> llama.cpp# make
> I ccache not found. Consider installing it for faster compilation.
> I llama.cpp build info: 
> I UNAME_S:   Linux
> I UNAME_P:   x86_64
> I UNAME_M:   x86_64
> I CFLAGS:    -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_LLAMAFILE  -std=c11   -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Werror=implicit-function-declaration -pthread -march=native -mtune=native -Wdouble-promotion
> I CXXFLAGS:  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -pthread  -march=native -mtune=native -Wno-array-bounds -Wno-format-truncation -Wextra-semi -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_LLAMAFILE
> I NVCCFLAGS: -std=c++11 -O3
> I LDFLAGS:
> I CC:        cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
> I CXX:       c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
> 
> cc  -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_LLAMAFILE  -std=c11   -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Werror=implicit-function-declaration -pthread -march=native -mtune=native -Wdouble-promotion    -c ggml.c -o ggml.o
> c++ -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -pthread  -march=native -mtune=native -Wno-array-bounds -Wno-format-truncation -Wextra-semi -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_LLAMAFILE  -c llama.cpp -o llama.o
> c++ -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -pthread  -march=native -mtune=native -Wno-array-bounds -Wno-format-truncation -Wextra-semi -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_LLAMAFILE  -c common/common.cpp -o common.o   
> c++ -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -pthread  -march=native -mtune=native -Wno-array-bounds -Wno-format-truncation -Wextra-semi -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_LLAMAFILE  -c common/sampling.cpp -o sampling.o
> c++ -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -pthread  -march=native -mtune=native -Wno-array-bounds -Wno-format-truncation -Wextra-semi -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_LLAMAFILE  -c common/grammar-parser.cpp -o grammar-parser.o
> : not foundld-info.sh: 2: 
> : not foundld-info.sh: 4:
> : not foundld-info.sh: 9:
> scripts/build-info.sh: 31: Syntax error: end of file unexpected (expecting "then")
> make: *** [Makefile:925: common/build-info.cpp] Error 2
> ```

这检查起来可能有点复杂。
不过字符问题一般都是中间解析哪里没对上导致的。
我不确定是不是模型的问题还是llama.cpp本身支持wsl就不好。
可以帮忙确认一下中文回复是都不可行还是只有minicpmv2.5我们这个模型不可行？

**Comment by hyphantom** [comment]
@tc-mb 感谢您的帮助，我回答一下我没有表达清晰的问题
1. 关于编译错误定位在模型的问题还是llama.cpp本身支持wsl就不好这2个选项上，应该可以排除模型的问题，应为只是在wsl下编译llama.cpp的过程中出错。
2. 为何使用wsl编译？因为在win下编译成功，但是没法运行中文，想尝试一下中文问答，想到wsl可能能避开win下的cmd问题。
3. win的cmd中文问答失败的详细：a. 在utf-8字符集下，输入问题，结果返回非法输入; b. 使用gbk字符集，模型可以返回结果，但是乱码
